### ISSUE TITLE
Branch v1.x is out of sync

### ISSUE THREAD

**Issue by nicolas-grekas** [amphp/sync#5]
composer installs it when minimum-stability = dev, but it shouldn't.

**Comment by kelunik** [comment]
Thanks for letting us know.

@trowski Do you remember why that branch exists at all? I guess because we planned to return a promise while releasing a lock, but rolled that back?

**Comment by kelunik** [comment]
I've deleted the branch, so it should be fine now. Unfortunately, GitHub's mobile site is broken and doesn't offer the delete button, even in desktop mode.

**Comment by nicolas-grekas** [comment]
composer still install `v1.x-dev eafe96a`
maybe something to clean on packagist?

**Comment by kelunik** [comment]
Yup, I've deleted it there. :+1:
