### ISSUE TITLE
Improve FileMutex to use amphp/file if available

### ISSUE THREAD

**Issue by enumag** [amphp/sync#8]
I noticed that the FileMutex is using the `\unlink()` function. But isn't this blocking? Shouldn't `\Amp\File\unlink()` be used instead?

https://github.com/amphp/sync/blob/master/src/FileMutex.php#L77

**Comment by kelunik** [comment]
Same applies to `fopen`, yes.

**Comment by enumag** [comment]
Is it okay to require amphp/file in composer.json?

**Comment by enumag** [comment]
I don't want it to use async API magically when available. Seems weird.

**Comment by enumag** [comment]
Imo we should either require amphp/file or throw exception if it isn't installed.

**Comment by kelunik** [comment]
Throwing would be a BC break. `amphp/file` depends on `amphp/parallel`, I'd rather avoid that dependency in `amphp/sync`, as `amphp/cache` depends on `amphp/sync` and `amphp/dns` depends on `amphp/cache`, where we removed `amphp/file` as a dependency some time ago on purpose.

**Comment by enumag** [comment]
Then maybe we should add a separate class that would use the amphp/file or throw?

**Comment by enumag** [comment]
AsyncFileMutex or something?

**Comment by enumag** [comment]
and rename FileMutex to BlockingFileMutex with alias for BC I'd say...

**Comment by kelunik** [comment]
We can add `AsyncFileMutex` to `amphp/file`, not sure whether we need the rename.

**Comment by enumag** [comment]
If it's in `amphp/file` then it becomes kinda hidden and ppl won't notice it. Renaming is necessary in my opinion to make it obvious that this class shouldn't actually be used.

**Comment by kelunik** [comment]
`amphp/file` is the right place for it, because it already depends on `amphp/sync` through `amphp/parallel`. If we release a new major version of `amphp/file` and have just a check here, things might break or get really hacky if we need to adapt.

**Comment by enumag** [comment]
Alright, I'll try to implement it and open a PR at amphp/file. Thanks!
